kind: Service
apiVersion: v1
metadata:
  name: rhel8-eap-service
  namespace: eap
spec:
  externalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ports:
    - protocol: TCP
      port: 22000
      targetPort: 22
      name: ssh
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  internalTrafficPolicy: Cluster
  allocateLoadBalancerNodePorts: true
  type: LoadBalancer
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    kubevirt.io/domain: rhel8-eap



